class User {
  final String? id;
  final String? simpleId; // 4-character simple ID (e.g., A3B7)
  final String name;
  final String email;
  final String phone;
  final String? profileImage;
  final String? address;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final bool isActive;
  final List<String> favoriteServices;

  User({
    this.id,
    this.simpleId,
    required this.name,
    required this.email,
    required this.phone,
    this.profileImage,
    this.address,
    this.createdAt,
    this.updatedAt,
    this.isActive = true,
    this.favoriteServices = const [],
  });

  // Create from Map
  factory User.fromMap(Map<String, dynamic> data, {String? id}) {
    return User(
      id: id ?? data['id'],
      simpleId: data['simpleId'],
      name: data['name'] ?? '',
      email: data['email'] ?? '',
      phone: data['phone'] ?? '',
      profileImage: data['profileImage'],
      address: data['address'],
      createdAt: data['createdAt'] is DateTime ? data['createdAt'] : (data['createdAt'] != null ? DateTime.parse(data['createdAt'].toString()) : null),
      updatedAt: data['updatedAt'] is DateTime ? data['updatedAt'] : (data['updatedAt'] != null ? DateTime.parse(data['updatedAt'].toString()) : null),
      isActive: data['isActive'] ?? true,
      favoriteServices: List<String>.from(data['favoriteServices'] ?? []),
    );
  }

  // Create a new user (simpleId will be auto-generated by database)
  factory User.create({
    required String name,
    required String email,
    required String phone,
    String? profileImage,
    String? address,
  }) {
    return User(
      simpleId: null, // Will be auto-generated by database trigger (format: AAA00001)
      name: name,
      email: email,
      phone: phone,
      profileImage: profileImage,
      address: address,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isActive: true,
      favoriteServices: const [],
    );
  }

  // Convert to Map
  Map<String, dynamic> toMap() {
    return {
      'simpleId': simpleId,
      'name': name,
      'email': email,
      'phone': phone,
      'profileImage': profileImage,
      'address': address,
      'isActive': isActive,
      'favoriteServices': favoriteServices,
      'createdAt': createdAt?.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(),
    };
  }

  // Copy with method
  User copyWith({
    String? id,
    String? simpleId,
    String? name,
    String? email,
    String? phone,
    String? profileImage,
    String? address,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? isActive,
    List<String>? favoriteServices,
  }) {
    return User(
      id: id ?? this.id,
      simpleId: simpleId ?? this.simpleId,
      name: name ?? this.name,
      email: email ?? this.email,
      phone: phone ?? this.phone,
      profileImage: profileImage ?? this.profileImage,
      address: address ?? this.address,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      isActive: isActive ?? this.isActive,
      favoriteServices: favoriteServices ?? this.favoriteServices,
    );
  }

  // Get display ID (simple ID if available, otherwise user ID)
  String get displayId => simpleId ?? id ?? 'N/A';

  // Check if user has a simple ID
  bool get hasSimpleId => simpleId != null && simpleId!.isNotEmpty;
}
