// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2FD7k_Sr8QeHbRUvHyOXivSiLtC33uVU',
    appId: '1:499888969163:web:e8ae4252d171d78213d24e',
    messagingSenderId: '499888969163',
    projectId: 'kromium-f338e',
    authDomain: 'kromium-f338e.firebaseapp.com',
    storageBucket: 'kromium-f338e.firebasestorage.app',
    measurementId: 'G-PEXQSYQN83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm6z4sxccmvJkuF8N4LscbcUWiKuRAzbw',
    appId: '1:499888969163:android:6dd63995f90cd08313d24e',
    messagingSenderId: '499888969163',
    projectId: 'kromium-f338e',
    storageBucket: 'kromium-f338e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2FD7k_Sr8QeHbRUvHyOXivSiLtC33uVU',
    appId: '1:499888969163:ios:6dd63995f90cd08313d24e',
    messagingSenderId: '499888969163',
    projectId: 'kromium-f338e',
    storageBucket: 'kromium-f338e.firebasestorage.app',
    iosBundleId: 'com.kronium.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2FD7k_Sr8QeHbRUvHyOXivSiLtC33uVU',
    appId: '1:499888969163:ios:6dd63995f90cd08313d24e',
    messagingSenderId: '499888969163',
    projectId: 'kromium-f338e',
    storageBucket: 'kromium-f338e.firebasestorage.app',
    iosBundleId: 'com.kronium.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2FD7k_Sr8QeHbRUvHyOXivSiLtC33uVU',
    appId: '1:499888969163:web:e8ae4252d171d78213d24e',
    messagingSenderId: '499888969163',
    projectId: 'kromium-f338e',
    authDomain: 'kromium-f338e.firebaseapp.com',
    storageBucket: 'kromium-f338e.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC2FD7k_Sr8QeHbRUvHyOXivSiLtC33uVU',
    appId: '1:499888969163:web:e8ae4252d171d78213d24e',
    messagingSenderId: '499888969163',
    projectId: 'kromium-f338e',
    authDomain: 'kromium-f338e.firebaseapp.com',
    storageBucket: 'kromium-f338e.firebasestorage.app',
  );

}